//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NW.WIDJobs.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NW.WIDJobs.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;!--[if lt IE 7]&gt;      &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9 lt-ie8 lt-ie7&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 7]&gt;         &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9 lt-ie8&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 8]&gt;         &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if gt IE 8]&gt;&lt;!--&gt;
        ///&lt;html lang=&quot;en&quot; class=&quot;no-js&quot;  data-pagetype=&quot;jobSearch&quot;&gt;
        ///&lt;!--&lt;![endif]--&gt;
        ///&lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Page01 {
            get {
                return ResourceManager.GetString("Page01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;!--[if lt IE 7]&gt;      &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9 lt-ie8 lt-ie7&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 7]&gt;         &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9 lt-ie8&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 8]&gt;         &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if gt IE 8]&gt;&lt;!--&gt;
        ///&lt;html lang=&quot;en&quot; class=&quot;no-js&quot;  data-pagetype=&quot;jobview&quot;&gt;
        ///&lt;!--&lt;![endif]--&gt;
        ///&lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;wi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Page01_PageItemExtended01 {
            get {
                return ResourceManager.GetString("Page01_PageItemExtended01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;!--[if lt IE 7]&gt;      &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9 lt-ie8 lt-ie7&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 7]&gt;         &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9 lt-ie8&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 8]&gt;         &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if gt IE 8]&gt;&lt;!--&gt;
        ///&lt;html lang=&quot;en&quot; class=&quot;no-js&quot;  data-pagetype=&quot;jobview&quot;&gt;
        ///&lt;!--&lt;![endif]--&gt;
        ///&lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;wi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Page01_PageItemExtended14 {
            get {
                return ResourceManager.GetString("Page01_PageItemExtended14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;!--[if lt IE 7]&gt;      &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9 lt-ie8 lt-ie7&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 7]&gt;         &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9 lt-ie8&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 8]&gt;         &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if gt IE 8]&gt;&lt;!--&gt;
        ///&lt;html lang=&quot;en&quot; class=&quot;no-js&quot;  data-pagetype=&quot;jobSearch&quot;&gt;
        ///&lt;!--&lt;![endif]--&gt;
        ///&lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Page01Alternate {
            get {
                return ResourceManager.GetString("Page01Alternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;!--[if lt IE 7]&gt;      &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9 lt-ie8 lt-ie7&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 7]&gt;         &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9 lt-ie8&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 8]&gt;         &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if gt IE 8]&gt;&lt;!--&gt;
        ///&lt;html lang=&quot;en&quot; class=&quot;no-js&quot;  data-pagetype=&quot;jobSearch&quot;&gt;
        ///&lt;!--&lt;![endif]--&gt;
        ///&lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Page02 {
            get {
                return ResourceManager.GetString("Page02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;!--[if lt IE 7]&gt;      &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9 lt-ie8 lt-ie7&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 7]&gt;         &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9 lt-ie8&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 8]&gt;         &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if gt IE 8]&gt;&lt;!--&gt;
        ///&lt;html lang=&quot;en&quot; class=&quot;no-js&quot;  data-pagetype=&quot;jobview&quot;&gt;
        ///&lt;!--&lt;![endif]--&gt;
        ///&lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;wi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Page02_PageItemExtended18 {
            get {
                return ResourceManager.GetString("Page02_PageItemExtended18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;!--[if lt IE 7]&gt;      &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9 lt-ie8 lt-ie7&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 7]&gt;         &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9 lt-ie8&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 8]&gt;         &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if gt IE 8]&gt;&lt;!--&gt;
        ///&lt;html lang=&quot;en&quot; class=&quot;no-js&quot;  data-pagetype=&quot;jobSearch&quot;&gt;
        ///&lt;!--&lt;![endif]--&gt;
        ///&lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Page02Alternate {
            get {
                return ResourceManager.GetString("Page02Alternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;!--[if lt IE 7]&gt;      &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9 lt-ie8 lt-ie7&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 7]&gt;         &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9 lt-ie8&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 8]&gt;         &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if gt IE 8]&gt;&lt;!--&gt;
        ///&lt;html lang=&quot;en&quot; class=&quot;no-js&quot;  data-pagetype=&quot;jobview&quot;&gt;
        ///&lt;!--&lt;![endif]--&gt;
        ///&lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;wi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Page03_PageItemExtended01 {
            get {
                return ResourceManager.GetString("Page03_PageItemExtended01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;!--[if lt IE 7]&gt;      &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9 lt-ie8 lt-ie7&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 7]&gt;         &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9 lt-ie8&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 8]&gt;         &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if gt IE 8]&gt;&lt;!--&gt;
        ///&lt;html lang=&quot;en&quot; class=&quot;no-js&quot;  data-pagetype=&quot;jobview&quot;&gt;
        ///&lt;!--&lt;![endif]--&gt;
        ///&lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;wi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Page03_PageItemExtended02 {
            get {
                return ResourceManager.GetString("Page03_PageItemExtended02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;!--[if lt IE 7]&gt;      &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9 lt-ie8 lt-ie7&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 7]&gt;         &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9 lt-ie8&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 8]&gt;         &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if gt IE 8]&gt;&lt;!--&gt;
        ///&lt;html lang=&quot;en&quot; class=&quot;no-js&quot;  data-pagetype=&quot;jobview&quot;&gt;
        ///&lt;!--&lt;![endif]--&gt;
        ///&lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;wi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Page03_PageItemExtended03 {
            get {
                return ResourceManager.GetString("Page03_PageItemExtended03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;!--[if lt IE 7]&gt;      &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9 lt-ie8 lt-ie7&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 7]&gt;         &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9 lt-ie8&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 8]&gt;         &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if gt IE 8]&gt;&lt;!--&gt;
        ///&lt;html lang=&quot;en&quot; class=&quot;no-js&quot;  data-pagetype=&quot;jobview&quot;&gt;
        ///&lt;!--&lt;![endif]--&gt;
        ///&lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;wi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Page03_PageItemExtended04 {
            get {
                return ResourceManager.GetString("Page03_PageItemExtended04", resourceCulture);
            }
        }
    }
}
