//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NW.WIDJobs.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NW.WIDJobs.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!-- saved from url=(0074)https://www.workindenmark.dk/job/6755865/COUNTRY-SALES-PRODUCT-RESPONSIBLE --&gt;
        ///&lt;html lang=&quot;en&quot; class=&quot;js history localstorage hashchange&quot; data-pagetype=&quot;jobview&quot;&gt;&lt;script type=&quot;text/javascript&quot; async=&quot;&quot; src=&quot;./View job _ Workindenmark_files/analytics.js.download&quot;&gt;&lt;/script&gt;&lt;script async=&quot;&quot; src=&quot;./View job _ Workindenmark_files/gtm.js.download&quot;&gt;&lt;/script&gt;&lt;script id=&quot;twitter-wjs&quot; src=&quot;./View job _ Workindenmark_files/widgets.js.download&quot;&gt;&lt;/script&gt;&lt;script type=&quot;text/javas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WorkInDenmark_Item {
            get {
                return ResourceManager.GetString("WorkInDenmark_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you speak Italian, and do you have great product knowledge about kids’ fashion in Italy? Would you like to contribute to the development of name it’s position in the Italian market? Then you may be just the one we are looking for to take on an exciting position in our dynamic sales team! We are on the lookout for a structured Country Sales &amp; Product Responsible with strong product knowledge, excellent coordination skills and professional proficiency in Italian to support our Sales Manager and sales team  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WorkInDenmark_Item_Description {
            get {
                return ResourceManager.GetString("WorkInDenmark_Item_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JACK &amp; JONESMONEY MAKER FOR INTERNATIONAL SALES TEAMBRANDE, DENMARK, DenmarkApply before: 31 December 2018Do you live and breathe for the next sale, and are you looking to kick-start your career working for an international fashion brand? Then we’ve got just the right challenge for you!   We are now open for applications for the JACK &amp; JONES MONEY MAKERS 2018 program - an intense talent d...
        ///See the complete text at Bestseller A/S
        ///http://about.bestseller.com/jobs/job-search/money-maker-for-international-s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WorkInDenmark_Item_Presentation {
            get {
                return ResourceManager.GetString("WorkInDenmark_Item_Presentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!--[if lt IE 7]&gt;      &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9 lt-ie8 lt-ie7&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 7]&gt;         &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9 lt-ie8&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 8]&gt;         &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if gt IE 8]&gt;&lt;!--&gt;
        ///&lt;html lang=&quot;en&quot; class=&quot;no-js&quot;  data-pagetype=&quot;jobview&quot;&gt;
        ///&lt;!--&lt;![endif]--&gt;
        ///&lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WorkInDenmark_ItemWithPresentation {
            get {
                return ResourceManager.GetString("WorkInDenmark_ItemWithPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--Page1--&gt; 
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;!--[if lt IE 7]&gt;      &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9 lt-ie8 lt-ie7&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 7]&gt;         &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9 lt-ie8&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 8]&gt;         &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if gt IE 8]&gt;&lt;!--&gt;
        ///&lt;html lang=&quot;en&quot; class=&quot;no-js&quot;  data-pagetype=&quot;jobSearch&quot;&gt;
        ///&lt;!--&lt;![endif]--&gt;
        ///&lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///        &lt;meta name=&quot;viewport [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WorkInDenmark_Page1 {
            get {
                return ResourceManager.GetString("WorkInDenmark_Page1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--Page2--&gt; 
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;!--[if lt IE 7]&gt;      &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9 lt-ie8 lt-ie7&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 7]&gt;         &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9 lt-ie8&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 8]&gt;         &lt;html lang=&quot;en&quot; class=&quot;no-js lt-ie9&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if gt IE 8]&gt;&lt;!--&gt;
        ///&lt;html lang=&quot;en&quot; class=&quot;no-js&quot;  data-pagetype=&quot;jobSearch&quot;&gt;
        ///&lt;!--&lt;![endif]--&gt;
        ///&lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///        &lt;meta name=&quot;viewport [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WorkInDenmark_Page2 {
            get {
                return ResourceManager.GetString("WorkInDenmark_Page2", resourceCulture);
            }
        }
    }
}
