//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NW.WIDJobs.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NW.WIDJobs.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;RunId&quot;: &quot;FakeRunId&quot;,
        ///  &quot;TotalResultCount&quot;: 2177,
        ///  &quot;TotalJobPages&quot;: 109,
        ///  &quot;Stage&quot;: 2,
        ///  &quot;IsCompleted&quot;: true,
        ///  &quot;JobPages&quot;: [
        ///    {
        ///      &quot;RunId&quot;: &quot;FakeRunId&quot;,
        ///      &quot;PageNumber&quot;: 1,
        ///      &quot;Response&quot;: &quot;This item has been exluded from the serializazion.&quot;
        ///    },
        ///    {
        ///      &quot;RunId&quot;: &quot;FakeRunId&quot;,
        ///      &quot;PageNumber&quot;: 2,
        ///      &quot;Response&quot;: &quot;This item has been exluded from the serializazion.&quot;
        ///    }
        ///  ],
        ///  &quot;JobPostings&quot;: &quot;This item has been exluded from the serializazion.&quot;,
        ///  &quot;JobPostingsExt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExplorationStage3AsJson {
            get {
                return ResourceManager.GetString("ExplorationStage3AsJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;RunId&quot;: &quot;FakeRunId&quot;,
        ///  &quot;TotalJobPages&quot;: 2,
        ///  &quot;TotalJobPostings&quot;: 40,
        ///  &quot;JobPostingsByHiringOrgName&quot;: {
        ///    &quot;TeamVikaren.dk, Århus ApS, Horsens Afdeling&quot;: 12,
        ///    &quot;Aarhus Universitet&quot;: 4,
        ///    &quot;Keepit A/S&quot;: 2,
        ///    &quot;Copenhagen Business School&quot;: 2,
        ///    &quot;RANDSTAD A/S&quot;: 2,
        ///    &quot;Plecto ApS&quot;: 2,
        ///    &quot;Novo Nordisk A/S&quot;: 2,
        ///    &quot;A.P. Møller - Mærsk A/S&quot;: 2,
        ///    &quot;Lokal Boligservice ApS&quot;: 1,
        ///    &quot;Danmarks Tekniske Universitet&quot;: 1,
        ///    &quot;BH HotelService ApS&quot;: 1,
        ///    &quot;Vikar DK A/S&quot;: 1,
        ///    &quot;KU - SCIE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExplorationStage3MCNumbersAsJson {
            get {
                return ResourceManager.GetString("ExplorationStage3MCNumbersAsJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;WorkSchedule&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Fuldtid&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 16,
        ///            &quot;Name&quot;: &quot;Deltid&quot;
        ///        }
        ///    ],
        ///    &quot;WorkConditions&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Almindelige vilkår&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 2,
        ///            &quot;Name&quot;: &quot;Fleksjob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 3,
        ///            &quot;Name&quot;: &quot;Skånejob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 4,
        ///            &quot;Name&quot;: &quot;Egnet t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage01_JobPostingExtended01_json {
            get {
                return ResourceManager.GetString("JobPage01_JobPostingExtended01_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;WorkSchedule&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Fuldtid&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 16,
        ///            &quot;Name&quot;: &quot;Deltid&quot;
        ///        }
        ///    ],
        ///    &quot;WorkConditions&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Almindelige vilkår&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 2,
        ///            &quot;Name&quot;: &quot;Fleksjob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 3,
        ///            &quot;Name&quot;: &quot;Skånejob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 4,
        ///            &quot;Name&quot;: &quot;Egnet t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage01_JobPostingExtended02_json {
            get {
                return ResourceManager.GetString("JobPage01_JobPostingExtended02_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;WorkSchedule&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Fuldtid&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 16,
        ///            &quot;Name&quot;: &quot;Deltid&quot;
        ///        }
        ///    ],
        ///    &quot;WorkConditions&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Almindelige vilkår&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 2,
        ///            &quot;Name&quot;: &quot;Fleksjob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 3,
        ///            &quot;Name&quot;: &quot;Skånejob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 4,
        ///            &quot;Name&quot;: &quot;Egnet t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage01_JobPostingExtended03_json {
            get {
                return ResourceManager.GetString("JobPage01_JobPostingExtended03_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;WorkSchedule&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Fuldtid&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 16,
        ///            &quot;Name&quot;: &quot;Deltid&quot;
        ///        }
        ///    ],
        ///    &quot;WorkConditions&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Almindelige vilkår&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 2,
        ///            &quot;Name&quot;: &quot;Fleksjob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 3,
        ///            &quot;Name&quot;: &quot;Skånejob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 4,
        ///            &quot;Name&quot;: &quot;Egnet t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage01_JobPostingExtended04_json {
            get {
                return ResourceManager.GetString("JobPage01_JobPostingExtended04_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;WorkSchedule&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Fuldtid&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 16,
        ///            &quot;Name&quot;: &quot;Deltid&quot;
        ///        }
        ///    ],
        ///    &quot;WorkConditions&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Almindelige vilkår&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 2,
        ///            &quot;Name&quot;: &quot;Fleksjob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 3,
        ///            &quot;Name&quot;: &quot;Skånejob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 4,
        ///            &quot;Name&quot;: &quot;Egnet t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage01_JobPostingExtended05_json {
            get {
                return ResourceManager.GetString("JobPage01_JobPostingExtended05_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;WorkSchedule&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Fuldtid&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 16,
        ///            &quot;Name&quot;: &quot;Deltid&quot;
        ///        }
        ///    ],
        ///    &quot;WorkConditions&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Almindelige vilkår&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 2,
        ///            &quot;Name&quot;: &quot;Fleksjob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 3,
        ///            &quot;Name&quot;: &quot;Skånejob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 4,
        ///            &quot;Name&quot;: &quot;Egnet t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage01_JobPostingExtended06_json {
            get {
                return ResourceManager.GetString("JobPage01_JobPostingExtended06_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;WorkSchedule&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Fuldtid&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 16,
        ///            &quot;Name&quot;: &quot;Deltid&quot;
        ///        }
        ///    ],
        ///    &quot;WorkConditions&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Almindelige vilkår&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 2,
        ///            &quot;Name&quot;: &quot;Fleksjob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 3,
        ///            &quot;Name&quot;: &quot;Skånejob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 4,
        ///            &quot;Name&quot;: &quot;Egnet t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage01_JobPostingExtended07_json {
            get {
                return ResourceManager.GetString("JobPage01_JobPostingExtended07_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;WorkSchedule&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Fuldtid&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 16,
        ///            &quot;Name&quot;: &quot;Deltid&quot;
        ///        }
        ///    ],
        ///    &quot;WorkConditions&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Almindelige vilkår&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 2,
        ///            &quot;Name&quot;: &quot;Fleksjob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 3,
        ///            &quot;Name&quot;: &quot;Skånejob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 4,
        ///            &quot;Name&quot;: &quot;Egnet t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage01_JobPostingExtended08_json {
            get {
                return ResourceManager.GetString("JobPage01_JobPostingExtended08_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;WorkSchedule&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Fuldtid&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 16,
        ///            &quot;Name&quot;: &quot;Deltid&quot;
        ///        }
        ///    ],
        ///    &quot;WorkConditions&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Almindelige vilkår&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 2,
        ///            &quot;Name&quot;: &quot;Fleksjob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 3,
        ///            &quot;Name&quot;: &quot;Skånejob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 4,
        ///            &quot;Name&quot;: &quot;Egnet t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage01_JobPostingExtended09_json {
            get {
                return ResourceManager.GetString("JobPage01_JobPostingExtended09_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;WorkSchedule&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Fuldtid&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 16,
        ///            &quot;Name&quot;: &quot;Deltid&quot;
        ///        }
        ///    ],
        ///    &quot;WorkConditions&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Almindelige vilkår&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 2,
        ///            &quot;Name&quot;: &quot;Fleksjob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 3,
        ///            &quot;Name&quot;: &quot;Skånejob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 4,
        ///            &quot;Name&quot;: &quot;Egnet t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage01_JobPostingExtended10_json {
            get {
                return ResourceManager.GetString("JobPage01_JobPostingExtended10_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;WorkSchedule&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Fuldtid&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 16,
        ///            &quot;Name&quot;: &quot;Deltid&quot;
        ///        }
        ///    ],
        ///    &quot;WorkConditions&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Almindelige vilkår&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 2,
        ///            &quot;Name&quot;: &quot;Fleksjob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 3,
        ///            &quot;Name&quot;: &quot;Skånejob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 4,
        ///            &quot;Name&quot;: &quot;Egnet t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage01_JobPostingExtended11_json {
            get {
                return ResourceManager.GetString("JobPage01_JobPostingExtended11_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;WorkSchedule&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Fuldtid&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 16,
        ///            &quot;Name&quot;: &quot;Deltid&quot;
        ///        }
        ///    ],
        ///    &quot;WorkConditions&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Almindelige vilkår&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 2,
        ///            &quot;Name&quot;: &quot;Fleksjob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 3,
        ///            &quot;Name&quot;: &quot;Skånejob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 4,
        ///            &quot;Name&quot;: &quot;Egnet t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage01_JobPostingExtended12_json {
            get {
                return ResourceManager.GetString("JobPage01_JobPostingExtended12_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;WorkSchedule&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Fuldtid&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 16,
        ///            &quot;Name&quot;: &quot;Deltid&quot;
        ///        }
        ///    ],
        ///    &quot;WorkConditions&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Almindelige vilkår&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 2,
        ///            &quot;Name&quot;: &quot;Fleksjob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 3,
        ///            &quot;Name&quot;: &quot;Skånejob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 4,
        ///            &quot;Name&quot;: &quot;Egnet t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage01_JobPostingExtended13_json {
            get {
                return ResourceManager.GetString("JobPage01_JobPostingExtended13_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;WorkSchedule&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Fuldtid&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 16,
        ///            &quot;Name&quot;: &quot;Deltid&quot;
        ///        }
        ///    ],
        ///    &quot;WorkConditions&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Almindelige vilkår&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 2,
        ///            &quot;Name&quot;: &quot;Fleksjob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 3,
        ///            &quot;Name&quot;: &quot;Skånejob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 4,
        ///            &quot;Name&quot;: &quot;Egnet t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage01_JobPostingExtended14_json {
            get {
                return ResourceManager.GetString("JobPage01_JobPostingExtended14_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;WorkSchedule&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Fuldtid&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 16,
        ///            &quot;Name&quot;: &quot;Deltid&quot;
        ///        }
        ///    ],
        ///    &quot;WorkConditions&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Almindelige vilkår&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 2,
        ///            &quot;Name&quot;: &quot;Fleksjob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 3,
        ///            &quot;Name&quot;: &quot;Skånejob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 4,
        ///            &quot;Name&quot;: &quot;Egnet t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage01_JobPostingExtended15_json {
            get {
                return ResourceManager.GetString("JobPage01_JobPostingExtended15_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;WorkSchedule&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Fuldtid&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 16,
        ///            &quot;Name&quot;: &quot;Deltid&quot;
        ///        }
        ///    ],
        ///    &quot;WorkConditions&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Almindelige vilkår&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 2,
        ///            &quot;Name&quot;: &quot;Fleksjob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 3,
        ///            &quot;Name&quot;: &quot;Skånejob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 4,
        ///            &quot;Name&quot;: &quot;Egnet t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage01_JobPostingExtended16_json {
            get {
                return ResourceManager.GetString("JobPage01_JobPostingExtended16_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;WorkSchedule&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Fuldtid&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 16,
        ///            &quot;Name&quot;: &quot;Deltid&quot;
        ///        }
        ///    ],
        ///    &quot;WorkConditions&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Almindelige vilkår&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 2,
        ///            &quot;Name&quot;: &quot;Fleksjob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 3,
        ///            &quot;Name&quot;: &quot;Skånejob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 4,
        ///            &quot;Name&quot;: &quot;Egnet t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage01_JobPostingExtended17_json {
            get {
                return ResourceManager.GetString("JobPage01_JobPostingExtended17_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;WorkSchedule&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Fuldtid&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 16,
        ///            &quot;Name&quot;: &quot;Deltid&quot;
        ///        }
        ///    ],
        ///    &quot;WorkConditions&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Almindelige vilkår&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 2,
        ///            &quot;Name&quot;: &quot;Fleksjob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 3,
        ///            &quot;Name&quot;: &quot;Skånejob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 4,
        ///            &quot;Name&quot;: &quot;Egnet t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage01_JobPostingExtended18_json {
            get {
                return ResourceManager.GetString("JobPage01_JobPostingExtended18_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;WorkSchedule&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Fuldtid&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 16,
        ///            &quot;Name&quot;: &quot;Deltid&quot;
        ///        }
        ///    ],
        ///    &quot;WorkConditions&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Almindelige vilkår&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 2,
        ///            &quot;Name&quot;: &quot;Fleksjob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 3,
        ///            &quot;Name&quot;: &quot;Skånejob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 4,
        ///            &quot;Name&quot;: &quot;Egnet t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage01_JobPostingExtended19_json {
            get {
                return ResourceManager.GetString("JobPage01_JobPostingExtended19_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;WorkSchedule&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Fuldtid&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 16,
        ///            &quot;Name&quot;: &quot;Deltid&quot;
        ///        }
        ///    ],
        ///    &quot;WorkConditions&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Almindelige vilkår&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 2,
        ///            &quot;Name&quot;: &quot;Fleksjob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 3,
        ///            &quot;Name&quot;: &quot;Skånejob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 4,
        ///            &quot;Name&quot;: &quot;Egnet t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage01_JobPostingExtended20_json {
            get {
                return ResourceManager.GetString("JobPage01_JobPostingExtended20_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Expression&quot;: {
        ///        &quot;ShowNearbyCriteria&quot;: true,
        ///        &quot;Offset&quot;: 0,
        ///        &quot;Count&quot;: 20,
        ///        &quot;SearchString&quot;: null,
        ///        &quot;SortValue&quot;: &quot;CreationDate&quot;,
        ///        &quot;Id&quot;: [],
        ///        &quot;EarliestPublicationDate&quot;: &quot;0001-01-01T00:00:00&quot;,
        ///        &quot;HotJob&quot;: false,
        ///        &quot;Abroad&quot;: false,
        ///        &quot;NearBy&quot;: null,
        ///        &quot;ExternalJob&quot;: null,
        ///        &quot;WorkPlaceNotStatic&quot;: null,
        ///        &quot;WorkHourMin&quot;: null,
        ///        &quot;WorkHourMax&quot;: null,
        ///        &quot;OnlyGeoPoints&quot;: false,
        ///        &quot;Facets&quot;: {
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage01_json {
            get {
                return ResourceManager.GetString("JobPage01_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;WorkSchedule&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Fuldtid&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 16,
        ///            &quot;Name&quot;: &quot;Deltid&quot;
        ///        }
        ///    ],
        ///    &quot;WorkConditions&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Almindelige vilkår&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 2,
        ///            &quot;Name&quot;: &quot;Fleksjob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 3,
        ///            &quot;Name&quot;: &quot;Skånejob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 4,
        ///            &quot;Name&quot;: &quot;Egnet t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage02_JobPostingExtended01_json {
            get {
                return ResourceManager.GetString("JobPage02_JobPostingExtended01_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;WorkSchedule&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Fuldtid&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 16,
        ///            &quot;Name&quot;: &quot;Deltid&quot;
        ///        }
        ///    ],
        ///    &quot;WorkConditions&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Almindelige vilkår&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 2,
        ///            &quot;Name&quot;: &quot;Fleksjob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 3,
        ///            &quot;Name&quot;: &quot;Skånejob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 4,
        ///            &quot;Name&quot;: &quot;Egnet t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage02_JobPostingExtended02_json {
            get {
                return ResourceManager.GetString("JobPage02_JobPostingExtended02_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;WorkSchedule&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Fuldtid&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 16,
        ///            &quot;Name&quot;: &quot;Deltid&quot;
        ///        }
        ///    ],
        ///    &quot;WorkConditions&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Almindelige vilkår&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 2,
        ///            &quot;Name&quot;: &quot;Fleksjob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 3,
        ///            &quot;Name&quot;: &quot;Skånejob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 4,
        ///            &quot;Name&quot;: &quot;Egnet t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage02_JobPostingExtended03_json {
            get {
                return ResourceManager.GetString("JobPage02_JobPostingExtended03_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;WorkSchedule&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Fuldtid&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 16,
        ///            &quot;Name&quot;: &quot;Deltid&quot;
        ///        }
        ///    ],
        ///    &quot;WorkConditions&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Almindelige vilkår&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 2,
        ///            &quot;Name&quot;: &quot;Fleksjob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 3,
        ///            &quot;Name&quot;: &quot;Skånejob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 4,
        ///            &quot;Name&quot;: &quot;Egnet t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage02_JobPostingExtended04_json {
            get {
                return ResourceManager.GetString("JobPage02_JobPostingExtended04_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;WorkSchedule&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Fuldtid&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 16,
        ///            &quot;Name&quot;: &quot;Deltid&quot;
        ///        }
        ///    ],
        ///    &quot;WorkConditions&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Almindelige vilkår&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 2,
        ///            &quot;Name&quot;: &quot;Fleksjob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 3,
        ///            &quot;Name&quot;: &quot;Skånejob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 4,
        ///            &quot;Name&quot;: &quot;Egnet t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage02_JobPostingExtended05_json {
            get {
                return ResourceManager.GetString("JobPage02_JobPostingExtended05_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;WorkSchedule&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Fuldtid&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 16,
        ///            &quot;Name&quot;: &quot;Deltid&quot;
        ///        }
        ///    ],
        ///    &quot;WorkConditions&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Almindelige vilkår&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 2,
        ///            &quot;Name&quot;: &quot;Fleksjob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 3,
        ///            &quot;Name&quot;: &quot;Skånejob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 4,
        ///            &quot;Name&quot;: &quot;Egnet t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage02_JobPostingExtended06_json {
            get {
                return ResourceManager.GetString("JobPage02_JobPostingExtended06_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;WorkSchedule&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Fuldtid&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 16,
        ///            &quot;Name&quot;: &quot;Deltid&quot;
        ///        }
        ///    ],
        ///    &quot;WorkConditions&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Almindelige vilkår&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 2,
        ///            &quot;Name&quot;: &quot;Fleksjob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 3,
        ///            &quot;Name&quot;: &quot;Skånejob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 4,
        ///            &quot;Name&quot;: &quot;Egnet t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage02_JobPostingExtended07_json {
            get {
                return ResourceManager.GetString("JobPage02_JobPostingExtended07_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;WorkSchedule&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Fuldtid&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 16,
        ///            &quot;Name&quot;: &quot;Deltid&quot;
        ///        }
        ///    ],
        ///    &quot;WorkConditions&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Almindelige vilkår&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 2,
        ///            &quot;Name&quot;: &quot;Fleksjob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 3,
        ///            &quot;Name&quot;: &quot;Skånejob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 4,
        ///            &quot;Name&quot;: &quot;Egnet t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage02_JobPostingExtended08_json {
            get {
                return ResourceManager.GetString("JobPage02_JobPostingExtended08_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;WorkSchedule&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Fuldtid&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 16,
        ///            &quot;Name&quot;: &quot;Deltid&quot;
        ///        }
        ///    ],
        ///    &quot;WorkConditions&quot;: [
        ///        {
        ///            &quot;Id&quot;: 1,
        ///            &quot;Name&quot;: &quot;Almindelige vilkår&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 2,
        ///            &quot;Name&quot;: &quot;Fleksjob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 3,
        ///            &quot;Name&quot;: &quot;Skånejob&quot;
        ///        },
        ///        {
        ///            &quot;Id&quot;: 4,
        ///            &quot;Name&quot;: &quot;Egnet t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage02_JobPostingExtended09_json {
            get {
                return ResourceManager.GetString("JobPage02_JobPostingExtended09_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE HTML&gt;
        ///&lt;html lang=&quot;da&quot;&gt;
        ///    &lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;/&gt;
        ///    &lt;title&gt;Jobannonce&lt;/title&gt;
        ///    
        ///    
        ///    &lt;meta name=&quot;template&quot; content=&quot;content-page&quot;/&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;/&gt;
        ///    
        ///
        ///    
        ///
        ///    
        ///
        ///	&lt;!-- OneTrust Cookie Consent - START --&gt;
        ///	&lt;!-- OneTrust Cookies Consent Notice start for www.novonordisk.dk --&gt;
        ///&lt;script type=&quot;text/javascript&quot; src=&quot;https://cdn.cookielaw.org/consent/ef63df1a-7968-4c59-944c-931160f6fff8/OtAutoBlock.js&quot;&gt;&lt;/script&gt;
        ///&lt;script  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage02_JobPostingExtended10 {
            get {
                return ResourceManager.GetString("JobPage02_JobPostingExtended10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE HTML&gt;
        ///&lt;html lang=&quot;da&quot;&gt;
        ///    &lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;/&gt;
        ///    &lt;title&gt;Jobannonce&lt;/title&gt;
        ///    
        ///    
        ///    &lt;meta name=&quot;template&quot; content=&quot;content-page&quot;/&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;/&gt;
        ///    
        ///
        ///    
        ///
        ///    
        ///
        ///	&lt;!-- OneTrust Cookie Consent - START --&gt;
        ///	&lt;!-- OneTrust Cookies Consent Notice start for www.novonordisk.dk --&gt;
        ///&lt;script type=&quot;text/javascript&quot; src=&quot;https://cdn.cookielaw.org/consent/ef63df1a-7968-4c59-944c-931160f6fff8/OtAutoBlock.js&quot;&gt;&lt;/script&gt;
        ///&lt;script  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage02_JobPostingExtended11 {
            get {
                return ResourceManager.GetString("JobPage02_JobPostingExtended11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html class=&quot;ku-bs theme-faelles&quot; lang=&quot;da&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;meta content=&quot;IE=edge&quot; http-equiv=&quot;X-UA-Compatible&quot;&gt;
        ///
        ///  &lt;!-- Responsive viewport: --&gt;
        ///  &lt;meta content=&quot;width=device-width, initial-scale=1.0&quot; name=&quot;viewport&quot;&gt;
        ///
        ///
        ///  &lt;!-- jQuery 3.1.0 --&gt;
        ///  &lt;script src=&quot;https://cms.ku.dk/jquery/jquery.min.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///
        ///  &lt;script src=&quot;https://cms.ku.dk/scripts_js/cookies/cookie_filters.js?ku_rollout_2021_07_01_version763&quot;&gt;&lt;/script&gt;
        ///
        ///
        ///  &lt;title&gt;Two postdoctoral positions in field-based  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage02_JobPostingExtended12 {
            get {
                return ResourceManager.GetString("JobPage02_JobPostingExtended12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;!-- Basic Meta tags --&gt;
        ///	&lt;meta charset=&quot;utf-8&quot;&gt;
        ///  &lt;meta http-equiv=&quot;x-ua-compatible&quot; content=&quot;IE=Edge&quot;&gt;
        ///	&lt;meta name=&quot;description&quot; content=&quot;LEO Pharma - Clinical disclosure specialist&quot;&gt;
        ///	&lt;meta name=&quot;designer&quot; content=&quot;Kenneth A. Amundsen, Visma Software Labs&quot;&gt;
        ///	&lt;meta name=&quot;author&quot; content=&quot;LEO Pharma&quot;&gt;
        ///	&lt;!-- Page title --&gt;
        ///	&lt;title&gt;LEO Pharma - Clinical disclosure specialist&lt;/title&gt;
        ///  &lt;!-- Favicon --&gt;
        ///	&lt;link rel=&quot;shortcut icon&quot; href=&quot;/files/favicon.ico&quot;&gt;
        ///	&lt;!-- Open Graph Protoc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage02_JobPostingExtended13 {
            get {
                return ResourceManager.GetString("JobPage02_JobPostingExtended13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en-US&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;!-- Application Properties --&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;chrome=1;IE=EDGE&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0, maximum-scale=2.0&quot;&gt;
        ///    &lt;meta name=&quot;referrer&quot; content=&quot;no-referrer-when-downgrade&quot;&gt;
        ///    
        ///
        ///	&lt;title&gt;Workday&lt;/title&gt;
        ///	&lt;link rel=&quot;icon&quot; href=&quot;/assets/images/favicon.ico&quot;&gt;
        ///
        ///    &lt;!-- Stylesheets --&gt;
        ///    &lt;style type=&quot;text [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage02_JobPostingExtended14 {
            get {
                return ResourceManager.GetString("JobPage02_JobPostingExtended14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot;&gt;
        ///  &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///  &lt;title&gt;Job Posting Page External&lt;/title&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0&quot;/&gt;
        ///  &lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; href=&quot;https://jobsearch.maersk.com/jobposting/css/styles.css&quot; media=&quot;all&quot;/&gt;
        ///  &lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; href=&quot;https://jobsearch.maersk.com/jobposting/css/print.css&quot; media=&quot;print&quot;/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage02_JobPostingExtended15 {
            get {
                return ResourceManager.GetString("JobPage02_JobPostingExtended15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html class=&quot;no-js&quot; prefix=&quot;og: http://ogp.me/ns#&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, maximum-scale=1&quot;&gt;
        ///
        ///
        ///&lt;meta name=&quot;description&quot; content=&quot;Vis ledig stilling på Aalborg Universitet&quot; /&gt;
        ///&lt;title&gt;Ledige stillinger på Aalborg Universitet&lt;/title&gt;
        ///
        ///&lt;!-- Cookie Information Consent --&gt;
        ///&lt;script id=&quot;CookieConsent&quot; src=&quot;https://policy.app.cookieinformation.com/uc.js&quot; data-culture=&quot;DA&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///&lt;!-- Rem [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage02_JobPostingExtended16 {
            get {
                return ResourceManager.GetString("JobPage02_JobPostingExtended16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot;&gt;
        ///  &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///  &lt;title&gt;Job Posting Page External&lt;/title&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0&quot;/&gt;
        ///  &lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; href=&quot;https://jobsearch.maersk.com/jobposting/css/styles.css&quot; media=&quot;all&quot;/&gt;
        ///  &lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; href=&quot;https://jobsearch.maersk.com/jobposting/css/print.css&quot; media=&quot;print&quot;/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage02_JobPostingExtended17 {
            get {
                return ResourceManager.GetString("JobPage02_JobPostingExtended17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot;&gt;
        ///  &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///  &lt;title&gt;Job Posting Page External&lt;/title&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0&quot;/&gt;
        ///  &lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; href=&quot;https://jobsearch.maersk.com/jobposting/css/styles.css&quot; media=&quot;all&quot;/&gt;
        ///  &lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; href=&quot;https://jobsearch.maersk.com/jobposting/css/print.css&quot; media=&quot;print&quot;/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage02_JobPostingExtended18 {
            get {
                return ResourceManager.GetString("JobPage02_JobPostingExtended18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html class=&quot;html5&quot; xml:lang=&quot;en-GB&quot; lang=&quot;en-GB&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///        &lt;head&gt;
        ///            &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge,chrome=1&quot; /&gt;
        ///            &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///                &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///                        &lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; href=&quot;/platform/bootstrap/3.4.1/css/bootstrap.min.css&quot; /&gt;
        ///                        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage02_JobPostingExtended19 {
            get {
                return ResourceManager.GetString("JobPage02_JobPostingExtended19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en-US&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;!-- Application Properties --&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;chrome=1;IE=EDGE&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0, maximum-scale=2.0&quot;&gt;
        ///    &lt;meta name=&quot;referrer&quot; content=&quot;no-referrer-when-downgrade&quot;&gt;
        ///    
        ///
        ///	&lt;title&gt;Workday&lt;/title&gt;
        ///	&lt;link rel=&quot;icon&quot; href=&quot;/assets/images/favicon.ico&quot;&gt;
        ///
        ///    &lt;!-- Stylesheets --&gt;
        ///    &lt;style type=&quot;text [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage02_JobPostingExtended20 {
            get {
                return ResourceManager.GetString("JobPage02_JobPostingExtended20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Expression&quot;: {
        ///        &quot;ShowNearbyCriteria&quot;: true,
        ///        &quot;Offset&quot;: 20,
        ///        &quot;Count&quot;: 20,
        ///        &quot;SearchString&quot;: null,
        ///        &quot;SortValue&quot;: &quot;CreationDate&quot;,
        ///        &quot;Id&quot;: [],
        ///        &quot;EarliestPublicationDate&quot;: &quot;0001-01-01T00:00:00&quot;,
        ///        &quot;HotJob&quot;: false,
        ///        &quot;Abroad&quot;: false,
        ///        &quot;NearBy&quot;: null,
        ///        &quot;ExternalJob&quot;: null,
        ///        &quot;WorkPlaceNotStatic&quot;: null,
        ///        &quot;WorkHourMin&quot;: null,
        ///        &quot;WorkHourMax&quot;: null,
        ///        &quot;OnlyGeoPoints&quot;: false,
        ///        &quot;Facets&quot;: {
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPage02_json {
            get {
                return ResourceManager.GetString("JobPage02_json", resourceCulture);
            }
        }
    }
}
